import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {MeshStandardMaterial,ShaderLib,Scene,PerspectiveCamera} from 'three';
import {buildBuildings} from '../src/buildings/render.mjs';
import {createFacadeDetailTextures} from '../src/buildings/high-detail.mjs';
import {installNightEmission} from '../src/environment/day-night.mjs';
import {FIDELITY,SoftBloomPass} from '../src/fidelity/pipeline.mjs';
import {RenderFidelity} from '../src/fidelity/look.mjs';
import {DayNightSystem} from '../src/environment/day-night.mjs';
import {TimeState} from '../src/app/foundation.mjs';
const data=JSON.parse(readFileSync('public/data/shibuya-scene-data.json'));

test('HIGH graphics calibrates shadow, exposure, environment and selective bloom to measured target',()=>{assert.deepEqual({shadow:FIDELITY.shadow,exposure:FIDELITY.exposure,day:FIDELITY.environmentDay,night:FIDELITY.environmentNight,strength:FIDELITY.bloomStrength,threshold:FIDELITY.bloomThreshold},{shadow:4096,exposure:1.08,day:.8,night:.55,strength:.55,threshold:3.8});const bloom=new SoftBloomPass();assert.equal(bloom.strength,.55);assert.equal(bloom.threshold,3.8);assert.equal(bloom.extract.uniforms.threshold.value,3.8);assert.ok(bloom.extract.fragmentShader.includes('b-threshold'));bloom.dispose();});

test('HIGH look applies measured exposure and environment response while MEDIUM restores its own values',()=>{const scene=new Scene(),renderer={toneMappingExposure:1,shadowMap:{enabled:false,type:null}},time=new TimeState(),environment=new DayNightSystem(scene,renderer,time),look=new RenderFidelity(scene,renderer,new PerspectiveCamera(),time,environment,{tier:'high'});look.maps={day:{texture:{name:'day'},dispose(){}},night:{texture:{name:'night'},dispose(){}}};environment.enable();look.refresh();assert.equal(renderer.toneMappingExposure,1.08);assert.equal(scene.environmentIntensity,.8);time.set('night');assert.equal(renderer.toneMappingExposure,1.08);assert.equal(scene.environmentIntensity,.55);look.setTier('medium');assert.equal(renderer.toneMappingExposure,1);assert.equal(scene.environmentIntensity,.28);look.dispose();environment.dispose();});

test('HIGH building detail adds deterministic wall and rooftop variety without changing MEDIUM budget',()=>{const b=buildBuildings(data);assert.equal(b.stats.tier,'medium');assert.equal(b.stats.approximateDrawCalls,8);assert.equal(b.stats.textures,0);b.setTier('high');const h=b.stats.highDetail;assert.ok(h);assert.equal(b.root.getObjectByName('buildings-high-detail').visible,true);assert.equal(h.batches.stain.instances,842);assert.equal(h.batches.sticker.instances,94);assert.equal(h.rooftopInstances,3505);assert.equal(b.stats.rooftopInstances,4206);assert.equal(h.textures,2);assert.deepEqual(h.textureDimensions,[[64,128],[128,160]]);assert.ok(h.wallInstances>3000&&h.triangles>100000);for(const name of Object.keys(h.batches))assert.ok(b.root.getObjectByName('buildings-high-'+name).isInstancedMesh,name);b.setTier('low');assert.equal(b.root.getObjectByName('buildings-high-detail').visible,false);assert.equal(b.stats.approximateDrawCalls,8);assert.equal(b.stats.textures,0);b.dispose();});

test('facade detail textures are color-managed, mipmapped and bounded',()=>{const maps=createFacadeDetailTextures();assert.deepEqual(Object.values(maps).map(t=>[t.image.width,t.image.height]),[[64,128],[128,160]]);for(const t of Object.values(maps)){assert.equal(t.colorSpace,'srgb');assert.equal(t.generateMipmaps,true);assert.equal(t.anisotropy,4);t.dispose();}});

test('night windows expose warm cream cool curtain and off channels above the bloom threshold',()=>{for(const mode of ['window','curtainWindow']){const material=new MeshStandardMaterial(),hook=installNightEmission(material,mode),shader={uniforms:{},vertexShader:ShaderLib.standard.vertexShader,fragmentShader:ShaderLib.standard.fragmentShader};material.onBeforeCompile(shader);assert.ok(shader.vertexShader.includes('s12WindowTint'));assert.ok(shader.fragmentShader.includes('0.65*s13Nightglow'));if(mode==='window'){for(const color of ['1.0,0.72,0.39','1.0,0.91,0.75','0.81,0.91,1.0'])assert.ok(shader.vertexShader.includes(color));assert.ok(shader.vertexShader.includes('seed<3.0?2.39:0.0'));}else assert.ok(shader.vertexShader.includes('s12Window=1.79'));hook.restore();material.dispose();}});
