import {CanvasTexture,DataTexture,SRGBColorSpace,LinearFilter,RGBAFormat} from 'three';
import {QUALITY,CATEGORIES} from './config.mjs';
const WORDS=['光庭','NEON ROOM','遊星','TONE','食堂 まど','FRAME','音の庭','CROSS','茶と空','LOOP','BOOK LAB','彩市','遊歩','KADO','LUMI','夜空'];
const COLORS=[['#16284e','#82e8ff'],['#d82c50','#fff3ce'],['#efc34d','#20252e'],['#e9eee5','#202e48'],['#7733a9','#ffe983'],['#087f87','#f9f5d8'],['#e66f2d','#172b4d'],['#252235','#e6a3fa']];
export function definitions(count=32){return Array.from({length:count},(_,i)=>({id:i,category:CATEGORIES[i%8],text:WORDS[i%WORDS.length],palette:COLORS[i%8],styleSeed:i,emissiveClass:i%8===6?'screen':'printed',priority:i%8===6?3:1,aspect:[3,2,.3,3,2,.5,2.2,1][i%8],regionAffinity:i%3===0?'centerGai':'any',sizeClass:i%8===4?'large':'small'}));}
export function atlasEntries(size,count){const cols=8,rows=4,padding=Math.max(4,size/256);return Array.from({length:count},(_,id)=>{const x=id%cols*size/cols,y=Math.floor(id/cols)*size/rows,w=size/cols,h=size/rows;return {id,x,y,w,h,padding,u0:(x+padding)/size,u1:(x+w-padding)/size,v0:1-(y+h-padding)/size,v1:1-(y+padding)/size};});}
export function paintCity(ctx,size,count){const entries=atlasEntries(size,count),defs=definitions(count);ctx.fillStyle='#17232b';ctx.fillRect(0,0,size,size);for(const e of entries){const d=defs[e.id],[bg,fg]=d.palette;ctx.fillStyle=bg;ctx.fillRect(e.x,e.y,e.w,e.h);ctx.save();ctx.beginPath();ctx.rect(e.x+e.padding,e.y+e.padding,e.w-2*e.padding,e.h-2*e.padding);ctx.clip();ctx.strokeStyle=fg;ctx.lineWidth=Math.max(2,e.w*.025);ctx.strokeRect(e.x+e.w*.08,e.y+e.h*.06,e.w*.84,e.h*.88);ctx.fillStyle=fg;ctx.textAlign='center';ctx.textBaseline='middle';const vertical=['blade','directory'].includes(d.category);if(vertical){ctx.font=`900 ${e.w*.27}px sans-serif`;const letters=(d.text.match(/[\u3000-\u9fff]/g)||d.text.replaceAll(' ','').slice(0,4).split('')).slice(0,4);letters.forEach((v,i)=>ctx.fillText(v,e.x+e.w*.5,e.y+e.h*(.2+i*.19),e.w*.7));}else{ctx.font=`900 ${e.w*.22}px sans-serif`;ctx.fillText(d.text,e.x+e.w*.5,e.y+e.h*.48,e.w*.82);ctx.font=`700 ${e.w*.09}px sans-serif`;ctx.fillText(['SELECT / 03','FOOD + MUSIC','TOKYO / ORIGINAL','OPEN / STUDIO'][e.id%4],e.x+e.w*.5,e.y+e.h*.72,e.w*.8);ctx.fillRect(e.x+e.w*.18,e.y+e.h*.22,e.w*.2,e.h*.06);}ctx.restore();}return entries;}
export function paintScreen(ctx,w,h){ctx.fillStyle='#102047';ctx.fillRect(0,0,w,h);for(let i=0;i<7;i++){ctx.fillStyle=['#7957ed','#f474a5','#51cee1'][i%3];ctx.beginPath();ctx.moveTo(w*(i*.19-.25),h);ctx.lineTo(w*(i*.19+.25),0);ctx.lineTo(w*(i*.19+.38),0);ctx.lineTo(w*(i*.19-.12),h);ctx.fill();}ctx.fillStyle='#102047';ctx.fillRect(w*.08,h*.24,w*.84,h*.52);ctx.fillStyle='#fff7d8';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`900 ${h*.22}px sans-serif`;ctx.fillText('CROSS VISION',w*.5,h*.45,w*.8);ctx.font=`700 ${h*.065}px sans-serif`;ctx.fillText('SHIBUYA  /  COLOR IN MOTION',w*.5,h*.65,w*.77);}
export function createSignAtlases({tier='medium',maxTextureSize=4096,canvasFactory}={}){const q=QUALITY[tier];if(!q)throw Error('Unknown signs tier');if(!(maxTextureSize>=128))throw Error('GPU texture limit too small');const cap=2**Math.floor(Math.log2(maxTextureSize)),size=Math.min(q.atlas,cap),screenWidth=Math.min(q.screen,cap),count=q.variants;
 const make=(w,h,paint)=>{const canvas=canvasFactory?canvasFactory():typeof document!=='undefined'?document.createElement('canvas'):null;let texture,mode;if(canvas){canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');if(!ctx)throw Error('Sign Canvas 2D unavailable');paint(ctx,w,h);texture=new CanvasTexture(canvas);mode='canvas';}else{texture=new DataTexture(new Uint8Array([255,255,255,255]),1,1,RGBAFormat);mode='cpu-placeholder';}texture.colorSpace=SRGBColorSpace;texture.minFilter=LinearFilter;texture.magFilter=LinearFilter;texture.generateMipmaps=false;texture.needsUpdate=true;return {texture,mode};};
 const city=make(size,size,(c,w)=>paintCity(c,w,count)),screen=make(screenWidth,screenWidth/2,paintScreen);let disposed=false;return {city,screen,entries:atlasEntries(size,count),definitions:definitions(count),size,screenWidth,count,dispose(){if(disposed)return;disposed=true;city.texture.dispose();screen.texture.dispose();}};
}
