import {Group,PlaneGeometry,BoxGeometry,Mesh,MeshStandardMaterial,BufferGeometry,Float32BufferAttribute,LineSegments,LineBasicMaterial} from 'three';
import {merge,InstancedBuilder,triangleCount} from '../geo/geometry.mjs';
import {inspectGeometry} from '../ground/render.mjs';
import {createSignAtlases} from './atlas.mjs';
import {buildSignModel} from './model.mjs';
import {REGIONS} from './config.mjs';

export function signFace(s,entry,reverse=false){const g=new PlaneGeometry(s.width,s.height);const uv=g.attributes.uv;for(let i=0;i<uv.count;i++)uv.setXY(i,entry.u0+uv.getX(i)*(entry.u1-entry.u0),entry.v0+uv.getY(i)*(entry.v1-entry.v0));const heading=s.heading+(reverse?Math.PI:0),dir=reverse?-1:1;g.rotateY(heading);g.translate(s.position[0]+s.normal[0]*(s.depth/2+.007)*dir,s.position[1],s.position[2]+s.normal[2]*(s.depth/2+.007)*dir);return g;}
function debugGeometry(model){const p=[],colors=[];const line=(a,b,color)=>{p.push(...a,...b);const rgb=[(color>>16&255)/255,(color>>8&255)/255,(color&255)/255];colors.push(...rgb,...rgb);};for(const s of [...model.signs,...model.rejected]){const color=s.issues?0xff3333:s.hero?0xffff77:REGIONS[s.region].color,center=s.position,n=s.normal,t=[n[2],0,-n[0]];line(center,center.map((v,i)=>v+n[i]*2),color);line([center[0]-.12,center[1],center[2]],[center[0]+.12,center[1],center[2]],color);const corners=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,y])=>[center[0]+t[0]*s.width/2*x,center[1]+y*s.height/2,center[2]+t[2]*s.width/2*x]);corners.forEach((c,i)=>line(c,corners[(i+1)%4],color));}const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(p,3));g.setAttribute('color',new Float32BufferAttribute(colors,3));return g;}
export function buildSignage(data,options={}){const start=performance.now(),model=options.model??buildSignModel(data,options);if(model.audit.major)throw Error('S7 placement audit failed');const atlas=createSignAtlases({...options,tier:model.tier}),root=new Group();root.name='s7-signage';
 const materials={print:new MeshStandardMaterial({map:atlas.city.texture,roughness:.72,emissive:0xffffff,emissiveMap:atlas.city.texture,emissiveIntensity:.12}),led:new MeshStandardMaterial({map:atlas.city.texture,roughness:.4,emissive:0xffffff,emissiveMap:atlas.city.texture,emissiveIntensity:.65}),heroScreen:new MeshStandardMaterial({map:atlas.screen.texture,roughness:.35,emissive:0xffffff,emissiveMap:atlas.screen.texture,emissiveIntensity:.65}),frame:new MeshStandardMaterial({color:0x25323d,roughness:.62})};
 const lists={print:[],led:[],heroScreen:[]},geometries=[],checks={},box=new BoxGeometry(1,1,1),frames=new InstancedBuilder(box,materials.frame,Math.max(1,model.signs.length));
 for(const s of model.signs){const entry=s.screenUV?{u0:s.screenUV[0]*.98+.01,u1:s.screenUV[1]*.98+.01,v0:.02,v1:.98}:atlas.entries[s.variant%atlas.count];const channel=s.screenUV?'heroScreen':s.category==='screen'?'led':'print';lists[channel].push(signFace(s,entry));if(s.category==='blade')lists[channel].push(signFace(s,entry,true));frames.add(...s.position,s.heading,[s.width+.015,s.height+.015,s.depth],0xffffff);}
 for(const [key,list] of Object.entries(lists)){if(!list.length)continue;const g=merge(list);list.forEach(g=>g.dispose());const mesh=new Mesh(g,materials[key]);mesh.name='signs-'+key;mesh.castShadow=false;root.add(mesh);checks[key]=inspectGeometry(g);geometries.push(g);}
 if(frames.count)root.add(frames.build());let debug=null;if(options.debug){const g=debugGeometry(model),mat=new LineBasicMaterial({vertexColors:true,depthTest:false});debug=new LineSegments(g,mat);debug.name='s7-anchor-normal-bounds-rejections-regions';debug.renderOrder=10;root.add(debug);}
 const stats={...model.stats,tier:model.tier,atlasCount:2,atlasDimensions:[[atlas.size,atlas.size],[atlas.screenWidth,atlas.screenWidth/2]],graphicVariants:atlas.count+1,atlasMode:atlas.city.mode,materials:4,batches:geometries.length+(frames.count?1:0),drawCallContribution:geometries.length+(frames.count?1:0),triangles:geometries.reduce((s,g)=>s+triangleCount(g),0)+frames.count*12,debugBatches:debug?1:0,checks,buildTimeMs:Math.round(performance.now()-start),emissiveDayOnly:true,pointLights:0};let disposed=false;
 return {root,model,atlas,stats,dispose(){if(disposed)return;disposed=true;root.removeFromParent();frames.dispose();box.dispose();geometries.forEach(g=>g.dispose());Object.values(materials).forEach(m=>m.dispose());atlas.dispose();if(debug){debug.geometry.dispose();debug.material.dispose();}root.clear();}};
}
