"use client";
import { useEffect, useRef, useState } from 'react';
import S1Data from './S1Data';
import {loadSceneData,summarize} from '../src/data/normalize.mjs';
import {buildDataDebug} from '../src/data/debug.mjs';
import { Switch } from '@/components/ui/switch';
import { CAMERAS, MODULES, PROFILES, parseConfig, TimeState, ModuleSystem } from '../src/app/foundation.mjs';
export default function Home(){
 const mount=useRef<HTMLDivElement>(null);const engine=useRef<any>(null);
 const [dataReport,setDataReport]=useState<any>(null);
 const [camera,setCamera]=useState('overview'),[tier,setTier]=useState('medium'),[time,setTime]=useState('day'),[modules,setModules]=useState<any[]>([]),[stats,setStats]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{let disposed=false;let cleanup=()=>{};
 (async()=>{const THREE=await import('three');const {OrbitControls}=await import('three/addons/controls/OrbitControls.js');if(disposed||!mount.current)return;
 const config=parseConfig(location.search),scene=new THREE.Scene();scene.background=new THREE.Color('#111923');
 const groups:any={};for(const name of ['world','dynamic','overlay']){groups[name]=new THREE.Group();groups[name].name=name;scene.add(groups[name]);}
 const canvas=document.createElement('canvas');const context=canvas.getContext('webgl2',{antialias:false,powerPreference:'high-performance'});const renderer=context?new THREE.WebGLRenderer({canvas,context,antialias:false,powerPreference:'high-performance'}):null;if(renderer){renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;}else{setError('この検証環境ではWebGL 2を利用できません。描画・FPSは未検証です。');}mount.current.appendChild(canvas);
 const view=new THREE.PerspectiveCamera(50,1,.1,2000),controls=new OrbitControls(view,canvas);controls.enableDamping=false;controls.maxDistance=1200;controls.minDistance=1;
 const clock=new TimeState(config.time);const system=new ModuleSystem(config,{scene,groups,renderer,camera:view,time:clock});
 for(const id of MODULES)system.register(id,id==='debug'?{build(){const grid=new THREE.GridHelper(500,50,0x50768a,0x243342);grid.name='inspection-grid';groups.overlay.add(grid);const axes=new THREE.AxesHelper(30);groups.overlay.add(axes);},dispose(){for(const child of [...groups.overlay.children]){child.geometry?.dispose();for(const m of Array.isArray(child.material)?child.material:[child.material])m?.dispose();groups.overlay.remove(child);}}}:{});
 system.start();
 // S1 data owns diagnostic lines in world; S0 overlay lifecycle is unchanged.
 let dataDebug:any=null;let dataGeneration=0;const dataAbort=new AbortController();
 const dataEntry=system.entries.get('data');dataEntry.enabled=false;
 dataEntry.hooks={build(){const generation=++dataGeneration;loadSceneData(undefined,{signal:dataAbort.signal}).then(data=>{if(disposed||generation!==dataGeneration||!dataEntry.enabled)return;setDataReport(summarize(data));dataDebug=buildDataDebug(data);groups.world.add(dataDebug.root);dataEntry.status='ready';setModules(system.snapshot());}).catch(e=>{if(disposed||dataAbort.signal.aborted||generation!==dataGeneration)return;dataEntry.status='failed';dataEntry.error=String(e);setDataReport({error:String(e)});setModules(system.snapshot());});},dispose(){dataGeneration++;dataDebug?.dispose();dataDebug=null;setDataReport(null);}};
 system.setEnabled('data',(config.only===null||config.only.includes('data'))&&!config.skip.includes('data'));
 const unsub=clock.subscribe((v:any)=>{system.timeChanged(v);setTime(v.value);});
 let currentTier=config.tier,currentCamera=config.camera;const resize=()=>{if(!mount.current)return;const w=mount.current.clientWidth,h=mount.current.clientHeight;const profile=PROFILES[currentTier];renderer?.setPixelRatio(Math.min(devicePixelRatio,profile.dpr)*profile.scale);renderer?.setSize(w,h);view.aspect=w/h;view.updateProjectionMatrix();};
 const preset=(id:string,applyTime=true)=>{const c=CAMERAS.find((v:any)=>v.id===id)!;view.position.fromArray(c.position);controls.target.fromArray(c.target);controls.update();currentCamera=id;setCamera(id);if(applyTime&&c.time)clock.set(c.time);};preset(config.camera,!config.explicitTime);resize();setTier(currentTier);setTime(clock.value);setModules(system.snapshot());
 const observer=new ResizeObserver(resize);observer.observe(mount.current);
 let frames=0,last=performance.now(),prev=last,raf=0;const frame=(now:number)=>{if(disposed)return;system.update(Math.min((now-prev)/1000,.1));prev=now;renderer?.render(scene,view);frames++;if(now-last>=500){const info=renderer?.info;setStats({fps:renderer?Number((frames*1000/(now-last)).toFixed(1)):null,triangles:info?.render.triangles??null,drawCalls:info?.render.calls??null,geometries:info?.memory.geometries??null,textures:info?.memory.textures??null,tier:currentTier,heapMB:(performance as any).memory?Number(((performance as any).memory.usedJSHeapSize/1048576).toFixed(1)):null,width:renderer?canvas.width:null,height:renderer?canvas.height:null});frames=0;last=now;}raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);
 const lost=(event:Event)=>{event.preventDefault();setError('WebGL context lost — reload to retry.');};canvas.addEventListener('webglcontextlost',lost);
 engine.current={preset,tier:(v:string)=>{currentTier=v;resize();setTier(v);},time:(v:string)=>clock.set(v),toggle:(id:string,v:boolean)=>{system.setEnabled(id,v);setModules(system.snapshot());}};
 cleanup=()=>{cancelAnimationFrame(raf);observer.disconnect();unsub();dataAbort.abort();system.dispose();controls.dispose();canvas.removeEventListener('webglcontextlost',lost);renderer?.dispose();canvas.remove();engine.current=null;};
 })().catch(e=>{if(!disposed)setError(String(e));});return()=>{disposed=true;cleanup();};},[]);
 return <main><header><div><span className="eyebrow">SCENE RECONSTRUCTION / RUN S1</span><h1>SHIBUYA <span>Foundation</span></h1></div><span className="badge">GEO DEBUG</span></header><div className="workspace"><aside><h2>Fixed cameras</h2><div className="cameras">{CAMERAS.map((c:any)=><button key={c.id} aria-pressed={camera===c.id} onClick={()=>engine.current?.preset(c.id)}>{c.label}</button>)}</div><h2>Performance profile</h2><div className="segmented">{Object.keys(PROFILES).map(v=><button key={v} aria-pressed={tier===v} onClick={()=>engine.current?.tier(v)}>{v.toUpperCase()}</button>)}</div><h2>Time state · stub</h2><div className="segmented">{['day','night'].map(v=><button key={v} aria-pressed={time===v} onClick={()=>engine.current?.time(v)}>{v.toUpperCase()}</button>)}</div><p className="note">時間状態のみ。照明・夜景は後続RUN。</p><h2>Modules</h2><div className="modules">{modules.map(m=><label key={m.id}><span>{m.id}<small>{m.status}</small></span><Switch checked={m.enabled} onCheckedChange={v=>engine.current?.toggle(m.id,v)} aria-label={m.id}/></label>)}</div></aside><section className="viewport"><div ref={mount} className="canvas"/><div className="view-label"><strong>{CAMERAS.find((c:any)=>c.id===camera)?.label}</strong><span>X east · Y up · −Z north / metres</span></div><div className="empty-label">S1 · 地理データ輪郭検査<span>ドラッグ：周回 / 右ドラッグ：移動 / ホイール：拡大</span></div>{error&&<div role="alert">{error}</div>}<div className="stats" aria-label="Performance stats">{stats?Object.entries(stats).map(([k,v])=><div key={k}><span>{k}</span><b>{v===null?'N/A':String(v)}</b></div>):'Renderer starting…'}</div></section></div><footer>world / dynamic / overlay <span>OSM Data + Geo Core · S1 only</span></footer><S1Data report={dataReport} enabled={modules.some(m=>m.id==='data'&&m.enabled)}/></main>;
}
