import {Group,PointLight,Scene,PMREMGenerator,Vector3,FogExp2,PCFSoftShadowMap,LinearMipmapLinearFilter,LinearFilter} from 'three';
import {Sky} from 'three/addons/objects/Sky.js';
import {createFidelityPipeline,noAO,FIDELITY} from './pipeline.mjs';
export class RenderFidelity{
 constructor(scene,renderer,camera,time,environment,{tier='medium'}={}){Object.assign(this,{scene,renderer,camera,time,environment,tier});this.roots=new Map();this.pipeline=null;this.maps=null;this.disposed=false;this.original={environment:scene.environment,intensity:scene.environmentIntensity,fog:scene.fog,shadowEnabled:renderer?.shadowMap.enabled,shadowType:renderer?.shadowMap.type};this.root=new Group();this.root.name='s163-local-lights';this.lights=[[-28,5,-23,115,0xffe4b8],[27,5,-19,100,0xbcd7ff],[-25,4,25,85,0xffd6a8],[28,5,27,75,0xc5deff]].map(([x,y,z,intensity,color])=>{const l=new PointLight(color,0,24,2);l.position.set(x,y,z);l.userData.nightIntensity=intensity;l.castShadow=false;this.root.add(l);return l;});scene.add(this.root);this.previousApplied=environment.onApplied;environment.onApplied=()=>{this.previousApplied?.();this.applyLook();};this.off=time.subscribe(()=>this.refresh());this.refresh();}
 prepare(){if(this.disposed||this.tier==='low'||!this.renderer)return;if(!this.maps){const generator=new PMREMGenerator(this.renderer),skyScene=new Scene(),sky=new Sky();sky.scale.setScalar(450);sky.material.uniforms.showSunDisc.value=false;skyScene.add(sky);const maps={};try{for(const mode of ['day','night']){sky.material.uniforms.turbidity.value=mode==='day'?4:8;sky.material.uniforms.rayleigh.value=mode==='day'?2:.6;sky.material.uniforms.sunPosition.value.copy(new Vector3(-.4,mode==='day'?.8:.1,.25));maps[mode]=generator.fromScene(skyScene,.04,.1,1000,{size:128}); }this.maps=maps;}catch(error){Object.values(maps).forEach(m=>m.dispose());throw error;}finally{generator.dispose();sky.geometry.dispose();sky.material.dispose();}}if(this.tier==='high'&&!this.pipeline)this.pipeline=createFidelityPipeline(this.renderer,this.scene,this.camera);this.refresh();}
 register(root){if(this.roots.has(root))return;const records=[];const max=this.renderer?.capabilities.getMaxAnisotropy()??1;root.traverse(o=>{if(!o.isMesh)return;records.push({o,cast:o.castShadow,receive:o.receiveShadow});o.userData.noAO=noAO(o);for(const m of Array.isArray(o.material)?o.material:[o.material])for(const t of [m?.map,m?.emissiveMap])if(t){const a=Math.min(max,o.name.startsWith('ground-')?8:4);if(t.anisotropy!==a||!t.generateMipmaps||t.minFilter!==LinearMipmapLinearFilter){t.anisotropy=a;t.generateMipmaps=true;t.minFilter=LinearMipmapLinearFilter;t.magFilter=LinearFilter;t.needsUpdate=true;}}});const removed=()=>{for(const r of records){r.o.castShadow=r.cast;r.o.receiveShadow=r.receive;}root.removeEventListener('removed',removed);this.roots.delete(root);this.refresh();};root.addEventListener('removed',removed);this.roots.set(root,{records,removed});this.refresh();}
 setTier(t){this.tier=t;this.refresh();}
 refresh(){if(!this.disposed)this.environment.apply();}
 applyLook(){if(this.disposed)return;const active=this.environment.active,high=active&&this.tier==='high',dark=active&&this.time.isDark();const main=this.environment.key;
 if(this.renderer){this.renderer.shadowMap.enabled=high;this.renderer.shadowMap.type=PCFSoftShadowMap;}main.castShadow=high;main.shadow.mapSize.set(FIDELITY.shadow,FIDELITY.shadow);main.shadow.radius=2;main.shadow.bias=-.0006;main.shadow.normalBias=.06;Object.assign(main.shadow.camera,{left:-85,right:85,top:85,bottom:-85,near:1,far:400});main.shadow.camera.updateProjectionMatrix();
 for(const r of this.environment.roots.values())for(const b of r.lights)if(high&&b.light.isDirectionalLight)b.light.intensity=0;if(high)main.intensity=dark?.16:1.65;
 for(const {records} of this.roots.values())for(const {o,cast,receive} of records){if(o.name==='s163-halo'){o.material.uniforms.night.value=dark?1:0;o.visible=this.tier!=='low'&&dark;}const opaque=!o.userData.noAO&&!(Array.isArray(o.material)?o.material.some(m=>m.transparent):o.material?.transparent);o.castShadow=high&&opaque&&(/^(crowd-(body[0-3]|head|hair[0-2])|buildings-wall|hero-(concrete|glass|metal|roof)|station-)/.test(o.name))||cast;o.receiveShadow=high&&opaque||receive;}
 const count=high?4:active&&this.tier==='medium'?2:0;this.lights.forEach((l,i)=>{l.visible=i<count;l.intensity=dark&&i<count?l.userData.nightIntensity:0;});
 this.scene.environment=active&&this.tier!=='low'&&this.maps?this.maps[this.time.value].texture:this.original.environment;this.scene.environmentIntensity=this.scene.environment!==this.original.environment?(dark?.28:.48):this.original.intensity;
 this.scene.fog=active?(this.fog??=new FogExp2(0x9fb5ce,.0007)):this.original.fog;if(active){this.fog.color.setHex(dark?0x070c16:0x9fb5ce);this.fog.density=dark?.0012:.0007;}
 }
 render(postprocess,wetEnabled){this.postprocessEnabled=postprocess;if(this.tier!=='high'||!postprocess||!this.pipeline)return false;this.pipeline.render(this.environment.active&&this.time.isDark(),wetEnabled);return true;}
 snapshot(){return {tier:this.tier,smaa:this.tier==='high'&&!!this.pipeline&&this.postprocessEnabled!==false,ao:this.tier==='high'&&!!this.pipeline&&this.postprocessEnabled!==false,aoScale:.5,shadowMap:this.tier==='high'?2048:0,environmentMap:this.scene.environment!==this.original.environment,localLights:this.lights.filter(l=>l.visible&&l.intensity>0).length,dprCap:1.5};}
 dispose(){if(this.disposed)return;this.disposed=true;this.environment.onApplied=this.previousApplied;this.off();for(const [root,r] of this.roots){root.removeEventListener('removed',r.removed);for(const b of r.records){b.o.castShadow=b.cast;b.o.receiveShadow=b.receive;}}this.roots.clear();this.pipeline?.dispose();if(this.maps)Object.values(this.maps).forEach(m=>m.dispose());this.root.removeFromParent();this.lights.forEach(l=>l.dispose());this.root.clear();this.scene.environment=this.original.environment;this.scene.environmentIntensity=this.original.intensity;this.scene.fog=this.original.fog;this.environment.key.castShadow=false;if(this.renderer){this.renderer.shadowMap.enabled=this.original.shadowEnabled;this.renderer.shadowMap.type=this.original.shadowType;}}
}
